//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cost { get; set; }
        public string time { get; set; }
        public string folder { get; set; }
        public string showTime { get; set; }
    }
}
