//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall_1
    {
        public int numberOfRow { get; set; }
        public Nullable<int> column1 { get; set; }
        public Nullable<int> column2 { get; set; }
        public Nullable<int> column3 { get; set; }
        public Nullable<int> column4 { get; set; }
        public Nullable<int> column5 { get; set; }
        public Nullable<int> column6 { get; set; }
        public Nullable<int> filmId { get; set; }
    }
}
